[package]
name = "glow-sdl2-context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.12.3"
sdl2 = "0.35.2"
with-context = { path = "../../../with-context" }
